include:
  - docker/compose/audiobookshelf.yml
  # - docker/compose/download-audio-stream-wfpk.yml
  - docker/compose/isponsorblocktv.yml
  - docker/compose/it-tools.yml
  - docker/compose/kavita.yml
  - docker/compose/navidrome.yml
  - docker/compose/resilio-sync.yml
  - docker/compose/stirling-pdf.yml
  # - docker/compose/syncthing.yml
