services:
  bind9:
    # *attempt to get this to run on raspberry pi 2 (32-bit), which canonical does not provide
    image: bind9:latest
    build:
      context: ../build/bind9_armv7
      dockerfile: Dockerfile
    container_name: bind9
    environment:
      # - BIND9_USER=root
      - TZ=${TZ}
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ${BIND_VOLUME_CACHE}:/var/cache/bind
      - ${BIND_VOLUME_CONFIG}:/etc/bind
      - ${BIND_VOLUME_RECORDS}:/var/lib/bind
    restart: unless-stopped
