services:
  navidrome:
    image: deluan/navidrome:0.53.3
    container_name: navidrome
    environment:
      ND_BASEURL: ""
      ND_ENABLETRANSCODINGCONFIG: true
      ND_LOGLEVEL: info
      ND_SCANSCHEDULE: 1h
      ND_SESSIONTIMEOUT: 24h
      TZ: ${TZ}
    ports:
      - 4533:4533
    user: ${PUID}:${GUID} # should be owner of volumes
    volumes:
      - ${NAVIDROME_VOLUME_CONFIG}:/data
      - ${NAVIDROME_VOLUME_MUSIC}:/music:ro
    restart: unless-stopped
