services:
  sonarr:
    # image: lscr.io/linuxserver/sonarr:4.0.9
    image: lscr.io/linuxserver/sonarr:${SONARR_VERSION}
    container_name: sonarr
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    # network_mode: "service:gluetun"
    volumes:
      - ${SONARR_VOLUME_CONFIG}:/config
      - ${SONARR_VOLUME_DATA}:/data # avoid common pitfalls: https://readarr.com/#downloads-v1-docker
    restart: unless-stopped
